// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbtfbndetzudbcfkfept.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidGZibmRldHp1ZGJjZmtmZXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDczMjMsImV4cCI6MjA2Njc4MzMyM30.rL0WgbWRTboEsjeXpm3i4w-56GdpnEbxrFWv3af9RLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);